### ISSUE TITLE
specs

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/cwl#1]
want to create a simple lib that makes dealing with cloudwatch logs easier.  We have this https://github.com/firstandthird/cwltail for tailing logs and https://github.com/firstandthird/aws-cli-utils/blob/master/lib/logs.js we had previously. So we create a single helper tool to handle that.  I'm thinking we should list out the commands and what they do before we get going.

//cc @ecwillis @orthagonal 

## Commands

- [x] `cwl groups` - list cloudwatch log groups
- [x] `cwl streams [groupname]` - list streams
- [x] `cwl tail [groupname] [?streamname]` - grab the last 10 mins of logs and then fetch every few seconds - pull in from cwltail
- [x] help messaging if running `cwl` by itself
- [x] make it work with `env.AWS_ACCESS_KEY_ID` and `env.AWS_SECRET_ACCESS_KEY`
- [x] `cwl search [groupname] [query]` - search group of logs for a specific query. need to figure out how to include streamname too.
- [ ] `cwl metric [groupname] [filtername]` - get the metric filter query and then do a search 
- [ ] `cwl cleanup [groupname] [days]` - remove streams that haven't had logs in the last X days

## Features
* option to pretty print output - use `purdy` to pretty print if json.  would be nice to color code nginx/apache logs

**Comment by jgallen23** [comment]
@orthagonal check off what ones are ready to be reviewed

**Comment by jgallen23** [comment]
@orthagonal added a couple of new items to the list. lets do those next

**Comment by jgallen23** [comment]
@orthagonal looking great!

- [ ] groups should not output json - use table output like streams

**Comment by jgallen23** [comment]
lets get search done and then call v1 done

**Comment by orthagonal** [comment]
@jgallen23  Updated up to 'search'.
