### ISSUE TITLE
logs command

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/cwl#6]
paginate through all logs starting from newest to oldest.  Maybe show last 50 logs and then have enter key show the next 50

**Comment by jgallen23** [comment]
feedback:

- [ ] change command to `logs` - not `log`
- [ ] make it an option to show log stream (default to false)
- [ ] make date format: MMYYDDD/HH:MM:SS (use moment maybe?)
- [ ] not pretty printing json logs (`prod-apps` stream as an example). should pretty printing be an optional thing?

**Comment by jgallen23** [comment]
@orthagonal ^

**Comment by orthagonal** [comment]
@jgallen23 should be ready for review
